# Generated by Django 6.0.3 on 2026-05-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banque', '0002_actionbanque_source_prevision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionbanque',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('traitee', 'Traitee')], default='en_cours', max_length=10),
        ),
        migrations.AlterField(
            model_name='actionbanque',
            name='type',
            field=models.CharField(choices=[('entree', 'Entree'), ('sortie', 'Sortie')], max_length=10),
        ),
    ]
