# Generated by Django 6.0.3 on 2026-04-14 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseurs', '0002_fournisseur_etat_regularite_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('echeance', models.DateField(blank=True, null=True)),
                ('mode_livraison', models.CharField(blank=True, max_length=100)),
                ('type_paiement', models.CharField(blank=True, max_length=100)),
                ('demande_achat', models.CharField(choices=[('ok', 'OK'), ('nok', 'NOK'), ('en_attente', 'En attente')], default='en_attente', max_length=20)),
                ('validation_direction', models.CharField(choices=[('ok', 'OK'), ('nok', 'NOK'), ('en_attente', 'En attente')], default='en_attente', max_length=20)),
                ('validation_finance', models.CharField(choices=[('ok', 'OK'), ('nok', 'NOK'), ('en_attente', 'En attente')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fournisseurs.fournisseur')),
            ],
        ),
    ]
