# Generated by Django 6.0.3 on 2026-05-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_update_commande_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='commande',
            name='demande_achat',
            field=models.FileField(blank=True, null=True, upload_to='commandes/docs/'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='validation_direction',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('ok', 'OK'), ('nok', 'NOK')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='validation_finance',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('ok', 'OK'), ('nok', 'NOK')], default='en_attente', max_length=20),
        ),
    ]
