# Generated by Django 6.0.3 on 2026-03-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('achat', 'Achat'), ('others', 'Others')], default='others', max_length=20),
        ),
    ]
