# Generated by Django 6.0.3 on 2026-04-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('achat', 'Achat'), ('others', 'Others'), ('responsable_technique', 'Responsable Technique')], default='others', max_length=30),
        ),
    ]
