# Generated by Django 6.0.3 on 2026-04-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_prevision', models.DateField()),
                ('categorie', models.CharField(blank=True, default='', max_length=255)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('traitee', 'Traitée'), ('cloturee', 'Clôturée')], default='en_cours', max_length=10)),
                ('semaine', models.IntegerField(choices=[(1, 'Semaine 1'), (2, 'Semaine 2'), (3, 'Semaine 3'), (4, 'Semaine 4')], default=1)),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['semaine', 'date_prevision'],
            },
        ),
    ]
