# Generated by Django 6.0.3 on 2026-05-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previsions', '0004_prevision_exclure_du_calcul'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SemaineCloture',
        ),
        migrations.AlterModelOptions(
            name='prevision',
            options={'ordering': ['semaine', 'date_prevision', 'id']},
        ),
        migrations.AlterField(
            model_name='prevision',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('traitee', 'Traitee'), ('cloturee', 'Cloturee')], default='en_cours', max_length=10),
        ),
        migrations.AlterField(
            model_name='prevision',
            name='type',
            field=models.CharField(choices=[('entree', 'Entree'), ('sortie', 'Sortie')], max_length=10),
        ),
    ]
