# Generated by Django 6.0.3 on 2026-04-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges_fixes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargefix',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
