# Generated by Django 6.0.3 on 2026-04-08 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=50)),
                ('couleur', models.CharField(blank=True, max_length=50)),
                ('etat_vidange', models.CharField(choices=[('normal', 'Normal'), ('proche', 'Proche'), ('depasee', 'Dépassée')], default='normal', max_length=20)),
                ('etat_assurance', models.CharField(choices=[('normal', 'Normal'), ('proche', 'Proche'), ('depasee', 'Dépassée')], default='normal', max_length=20)),
                ('etat_vignette', models.CharField(choices=[('normal', 'Normal'), ('proche', 'Proche'), ('depasee', 'Dépassée')], default='normal', max_length=20)),
                ('etat_revision', models.CharField(choices=[('normal', 'Normal'), ('proche', 'Proche'), ('depasee', 'Dépassée')], default='normal', max_length=20)),
                ('etat_voiture', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('en_panne', 'En panne')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('personne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DossierVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_echeance_assurance', models.DateField(blank=True, null=True)),
                ('date_echeance_visite', models.DateField(blank=True, null=True)),
                ('date_echeance_vignette', models.DateField(blank=True, null=True)),
                ('km_actuel', models.IntegerField(blank=True, null=True)),
                ('km_next_vidange', models.IntegerField(blank=True, null=True)),
                ('nombre_vidange', models.IntegerField(default=0)),
                ('vehicule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to='vehicules.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_souhaitee', models.DateField()),
                ('statut_validation', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('date_retour', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attribue_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_vehicule_attribuees', to=settings.AUTH_USER_MODEL)),
                ('demande_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_vehicule_faites', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='vehicules.vehicule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('vidange', 'Vidange'), ('vignette', 'Vignette'), ('assurance', 'Assurance'), ('lavage', 'Lavage'), ('depannage', 'Dépannage')], max_length=20)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='vehicules.vehicule')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
