# Generated by Django 6.0.3 on 2026-05-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0002_vehicule_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionvehicule',
            name='type',
            field=models.CharField(choices=[('vidange', 'Vidange'), ('vignette', 'Vignette'), ('assurance', 'Assurance'), ('lavage', 'Lavage'), ('depannage', 'Depannage')], max_length=20),
        ),
        migrations.AlterField(
            model_name='demandevehicule',
            name='statut_validation',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Valide'), ('refuse', 'Refuse')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='etat_assurance',
            field=models.CharField(choices=[('normal', 'Normal'), ('proche', 'Proche'), ('depasee', 'Depassee')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='etat_revision',
            field=models.CharField(choices=[('normal', 'Normal'), ('proche', 'Proche'), ('depasee', 'Depassee')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='etat_vidange',
            field=models.CharField(choices=[('normal', 'Normal'), ('proche', 'Proche'), ('depasee', 'Depassee')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='etat_vignette',
            field=models.CharField(choices=[('normal', 'Normal'), ('proche', 'Proche'), ('depasee', 'Depassee')], default='normal', max_length=20),
        ),
    ]
