# Generated by Django 6.0.3 on 2026-04-08 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('etat', models.CharField(choices=[('confirme', 'Confirmé'), ('en_cours', 'En cours'), ('bloque', 'Bloqué'), ('termine', 'Terminé'), ('receptionne', 'Réceptionné')], default='confirme', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterielChantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('etat', models.CharField(choices=[('confirme', 'Confirmé'), ('bloque', 'Bloqué'), ('commande', 'Commandé'), ('livre', 'Livré')], default='confirme', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanificationChantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planifications', to='chantiers.chantier')),
                ('technicien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planifications', to='equipe.technicien')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('chantier', 'technicien', 'date')},
            },
        ),
    ]
