# Generated by Django 6.0.3 on 2026-04-08 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChefEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='equipe/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='equipe/photos/')),
                ('niveau', models.CharField(choices=[('confirme', 'Technicien Confirmé'), ('operationnel', 'Technicien Opérationnel'), ('junior', 'Technicien Junior')], default='junior', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='techniciens', to='equipe.chefequipe')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='EtatMaterielTechnicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couleur', models.CharField(choices=[('vert', 'Vert'), ('orange', 'Orange'), ('rouge', 'Rouge'), ('gris', 'Gris')], default='vert', max_length=10)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etats_techniciens', to='equipe.materiel')),
                ('technicien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etats_materiels', to='equipe.technicien')),
            ],
            options={
                'unique_together': {('technicien', 'materiel')},
            },
        ),
    ]
