# Generated by Django 6.0.3 on 2026-04-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='etat_regularite_override',
            field=models.CharField(blank=True, choices=[('en_cours', 'En cours'), ('depasee', 'Dépassée'), ('renouvelee', 'Renouvelée')], default='', max_length=20),
        ),
    ]
