# Generated by Django 6.0.3 on 2026-05-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0003_fournisseur_regularite_depassee_notified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='etat_regularite_override',
            field=models.CharField(blank=True, choices=[('en_cours', 'En cours'), ('depasee', 'Depassee'), ('renouvelee', 'Renouvelee')], default='', max_length=20),
        ),
    ]
