# Generated by Django 6.0.3 on 2026-04-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0002_actioncaisse_source_action'),
        ('charges_variables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargevariable',
            name='source_action_caisse',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='charge_variable_liee',
                to='caisse.actioncaisse',
            ),
        ),
    ]
