# Generated by Django 6.0.3 on 2026-05-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges_variables', '0002_chargevariable_source_action_caisse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargevariable',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('traitee', 'Traitee')], default='en_cours', max_length=20),
        ),
    ]
