# Generated by Django 6.0.3 on 2026-04-08 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaissePersonnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('solde_initial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Caisse Personnelle',
            },
        ),
        migrations.CreateModel(
            name='SoldeCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solde Caisse',
            },
        ),
        migrations.CreateModel(
            name='ActionCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('titre', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('charge_variable', 'Charge Variable'), ('vehicule', 'Véhicule'), ('transport', 'Transport'), ('administratif', 'Charges administratives'), ('equipe', 'Dépenses équipe'), ('entretien', 'Entretien & nettoyage'), ('autre', 'Autre')], max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('personne', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='caisse/photos/')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('traitee', 'Traitée')], default='en_cours', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_caisse_principale', models.BooleanField(default=False)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
                ('caisse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='caisse.caissepersonnelle')),
            ],
            options={
                'verbose_name': 'Action Caisse',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
