# Generated by Django 6.0.3 on 2026-04-02 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActionSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('categorie', models.CharField(blank=True, default='', max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('traitee', 'Traitée')], default='en_cours', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='salaires.salarie')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
