# Generated by Django 6.0.4 on 2026-04-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewIrisDashboardRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('devis', models.CharField(blank=True, default='', max_length=255)),
                ('etat_po', models.CharField(blank=True, default='', max_length=255)),
                ('etat_facture', models.CharField(blank=True, default='', max_length=255)),
                ('service_newiris', models.CharField(blank=True, default='', max_length=255)),
                ('client', models.CharField(blank=True, default='', max_length=255)),
                ('contact', models.CharField(blank=True, default='', max_length=255)),
                ('service_client', models.CharField(blank=True, default='', max_length=255)),
                ('categorie', models.CharField(blank=True, default='', max_length=255)),
                ('chantier', models.CharField(blank=True, default='', max_length=255)),
                ('ca_ht', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('ca_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('source_key', models.CharField(max_length=500, unique=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'newiris_dashboard_records',
                'ordering': ['-annee', '-mois', 'devis'],
            },
        ),
    ]
